image: alsoedit/chat_web

clone:
  depth: full

pipelines:
  default:
    - step:
        caches:
          - node
        script:
          - npm install
          - npm test
          - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          - docker build -t alsoedit/chat_web:$BITBUCKET_COMMIT .
          - docker push alsoedit/chat_web:$BITBUCKET_COMMIT
          - git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD
        services: 
          - mongo 

definitions: 
  services: 
    mongo: 
      image: mongo

options:
  docker: true