
version: "2.0"
services:
  mongoDB:
    image: mongo
    ports:
      - "27017:27017"

  web:
    build: .
    ports:
      - "3000:3000"
      - "8080:8080"
    links:
      - mongoDB
